project:
  type: book
  output-dir: docs

book:
  title: "TAPIR: Transcript analysis pipelines in R"
  author: "The team"
  date: "5/29/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - eda.qmd
    - testing.qmd
    - post-dtu.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual
