# Exploratory data analysis

How can we explore transcript expression from long read data...

Let's load some data...

```{r}
library(here)
url <- "https://github.com/gandallab/Dev_Brain_IsoSeq/raw/main/data/cp_vz_0.75_min_7_recovery_talon_abundance_filtered.tsv.gz"
filename <- basename(url)
path <- here("data",filename)
if (!file.exists(path)) {
  download.file(url, path)
}
```

```{r}
library(readr)
raw_abundance_table <- read_delim(path)
dim(raw_abundance_table)
colnames(raw_abundance_table)
raw_abundance_table[1:5,1:15]
```

```{r}
library(dplyr)
library(tidyr)
raw_abundance_table |>
  select(contains(c("VZ","CP"))) |>
  summarize(across(everything(), sum))
```

```{r}
library(here)
filename <- "cp_vz_0.75_min_7_recovery_talon_abundance_filtered.tsv.gz"
path <- here("data",filename)
library(readr)
raw_abundance_table <- read_delim(path)
dim(raw_abundance_table)
colnames(raw_abundance_table)
```

```{r}
library(dplyr)
counts <- raw_abundance_table |>
  select(gene_id = annot_gene_id,
         feature_id = annot_transcript_id,
         contains(c("VZ","CP")))
counts <- counts |>
  rename_with(.cols = contains(c("VZ","CP")),
              \(x) paste0("s", x))
library(tidyr)
samples <- tibble(sample_id = colnames(counts)[-c(1:2)]) |>
  separate(sample_id, into=c("unit","rep","condition"), sep="_", remove=FALSE) |>
  mutate_at(c("rep","condition"), factor)
```
